### ISSUE TITLE
Bug? | Weird Tx/Rx Disconnect

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#221]
Latest firmware on R9M (Tx) and R9MX (Rx), within ~5 minutes of having serial connection get:
- Tx reports Rx is disconnected (red LED), Rx appears connected (green LED)
- Rx still outputs RC data over CRSF
- Lua shows only Tx, no Telemetry elements

Switching to Mavlink instead of MavlinkX seems to make it go away.  Issue seems similar to previously reported issue when using GCC 12.  No problem with connection when there is not an active serial connection.

**Comment by olliw42** [comment]
do we know a last good version/commit?

**Comment by jlpoltrack** [comment]
> do we know a last good version/commit?

1.3.00 Release looks good.

**Comment by olliw42** [comment]
ups ... that's a long way back ...

**Comment by jlpoltrack** [comment]
Got this disconnect behavior on 1.3.01:

HEAD is now at 15c198f6 v bump 1.3.01 (=dev)

Full hash - 15c198f61602ca500fbb7527fb90dac924c1130e

**Comment by olliw42** [comment]
@jlpoltrack don't fully understand

you're saying, "v1.3 (release)" or f12d6803 is ok, but already "v bump 1.3.01 (=dev)" or 15c198f6 is not ??

**Comment by olliw42** [comment]
@jlpoltrack @brad112358 
I seem to get the very same behavior
what I did is
- checked out 15c198f
- since I find it easier to do the testing with using the RadioMaster Bandit instead of the R9M (has display, and I'm used to it's fail behavior now) I added the few lines which are needed to get the RM Bandit to compile and work (platformio.ini, hal, and disp stuff)

when I have mavlinkX enabled it "chrashes" either at startup or soon after power up. With mavlinkX disabled it all seems fine.
(even when mavlinkX is disabled LQ is often below 100%, like 90%-ish low, not sure why that is, feels like before Brad's AFC finding, but that's another story)

I really can't understand that different behavior now. I'm absolutely sure that I have not updated my STM32Ide, and it says version 1.13.2, and the gcc is 11.3.rel1.

ANY idea as to why this can be ??

**Comment by olliw42** [comment]
next finding
replaced the R9MX by an ELRS GENERIC 900 (not sure what brand it is) ... and the issues seems to not exist, runs in mavlinkX just fine 
-> this suggests that the issue is specific to STM32
can anyone of you confirm that finding?

**Comment by jlpoltrack** [comment]
Thanks for confirming you see same.  Perhaps one extra piece I can add - when the 'crash' happens, power cycling the Rx seems to resolve which I don't quite understand.

**Comment by olliw42** [comment]
> when the 'crash' happens, power cycling the Rx seems to resolve which I don't quite understand.

same here. My interpretation is that some fields get reset and it can start again - might be totally wrong track though

> Have power meter hooked up to Rx, when 'crash' happens Rx still continues to transmit something.

when I use the ELRS generic 900, I do see the same.

so, at least we seem to see the same sympthoms ... that's good ... but I just can't make any sense of it yet.

so far I was speculating, as we had the issue "just" with the gcc12, that there is somewhere some memory leak and that some variable gets overriden ... the fact that gcc12 did/does arrange the variables differently in memory I considered supporting this view ... but now we see this for two different compiler, and "only" for sx1276 ...

**Comment by olliw42** [comment]
> Have power meter hooked up to Rx, when 'crash' happens Rx still continues to transmit something.

so, the rx seems to be happy to transmit ... question is thus if (C) the receiver is sending invalid frames so that the tx receives but rejects them (e.g. wrong bind phrase, wrong frequency, wrong header or crc, etc. pp) or is it indeed (B) that the tx stops receiving them.

since it's not easy to have debug output on the bandit I find that difficult to inversigate ... I guess I need to get using the R9M LOL

**Comment by jlpoltrack** [comment]
> since it's not easy to have debug output on the bandit I find that difficult to inversigate ... I guess I need to get using the R9M LOL

If you're keen - you can use JRPin5 on Bandit as a UART Output - it is pin 13. https://github.com/ExpressLRS/targets/blob/master/TX/Radiomaster%20Bandit%20Micro.json#L2-L3

**Comment by olliw42** [comment]
ah, intersting idea
what SERIAl would I have to use, SERIAL and SERIAL1 are already used up ....
can I use SERIAL2?

**Comment by jlpoltrack** [comment]
> can I use SERIAL2?

Yea, e.g. https://github.com/G6EJD/ESP32-Using-Hardware-Serial-Ports/blob/master/ESP32_Using_Serial2.ino#L17

**Comment by olliw42** [comment]
but how would I set it up, out lib needs bot rx and tx ot be specified, but they are on the same pin ... is this no problem?

**Comment by olliw42** [comment]
ah, I set RX to -1 ??

**Comment by jlpoltrack** [comment]
> ah, I set RX to -1 ??

That should work, same as done for RC Out on RP4-TD https://github.com/olliw42/mLRS/blob/main/mLRS/Common/hal/esp/rx-hal-radiomaster-rp4td-2400-esp32.h#L27

**Comment by olliw42** [comment]
it seems that in the failure mode the rx sends and the tx receives ... not sure yet what makes the tx not accept the packets

**Comment by tmcadam** [comment]
Just to confuse matters further. 

I noticed that by chance I have my R9M and BAYCK NANO PRO 900 at version 1.3.01, so gave them a bench test. I don't seem to see these issues with `mavlinkx` or `mavlink` set. I have a telemetry stream running also. Stable connection for well over 10 mins.

**Comment by olliw42** [comment]
some more data point ... the tx receives an incorrect sync word when the issue occurs it should be 0x7C85 but suddenly becomes 0x85D5
... does it miss a byte ??

**Comment by jlpoltrack** [comment]
This sync word from the status frame?  (Not the LoRa sync word?)

**Comment by olliw42** [comment]
yes, that's the sync word send over air, and checked here: https://github.com/olliw42/mLRS/blob/main/mLRS/CommonTx/mlrs-tx.cpp#L317-L319

when using the R9MX it changes from 0x7C85 (correct) to 0x5220 ...

**Comment by olliw42** [comment]
when one repowers the tx, when the rx still sends the incorrect sync word ... 
-> it seems the issue actually happens in the rx ,,, it would explain why one has to repower the rx wheras repowering the tx does not cure the issue
am trying to confirm by adding debug to the rx

**Comment by olliw42** [comment]
come on ... when I add a debug line on the R9MX side to print the syncword ... when it just works and works ... if I outcomment this line, the issue shows ...

**Comment by jlpoltrack** [comment]
Syncword is getting optimized out somehow without the print function present?

**Comment by olliw42** [comment]
I've put the dbg line in various places ... same behavior

how can we figure out if it's "optimized out"?

**Comment by olliw42** [comment]
if it's such a thing, wouldn't it be strange that two different compiler would do the same "mistake"

**Comment by olliw42** [comment]
@rotorman out of desperation, you happen to have any idea on such an issue?

**Comment by olliw42** [comment]
this all just does not make any sense
- with the debug line `dbg.puts("\n>x");dbg.puts(u16toHEX_s(Config.FrameSyncWord));dbg.puts(",");dbg.puts(u16toHEX_s(rxFrame.sync_word));` at the end of do_transmit() it runs and runs
- with `dbg.puts("\n>x");dbg.puts(u16toHEX_s(Config.FrameSyncWord));` or `dbg.puts("\n>x");dbg.puts(u16toHEX_s(rxFrame.sync_word));` the issue soon happens, but the debug output is always the correct 7C85, even though the tx receives 85D5

if the issue depends on what code I run on the receiver, one would think that the tx isn't responsible for getting a 85D5 ...

**Comment by jlpoltrack** [comment]
Just some wild thoughts - could the memory for the OTA get statically defined?  Or perhaps some variables can be marked volatile?

**Comment by olliw42** [comment]
> Just some wild thoughts - could the memory for the OTA get statically defined? Or perhaps some variables can be marked volatile?

statically I don't understand well, volatile yeah but which ones need that?

am reading this https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8
I have for a longer while the suspicion that the various typcasting which is going on with some structs may be an issue...

**Comment by brad112358** [comment]
I have, so far, been unable to reproduce this.  I have upgraded my R9M ACCST (Older R9M) and R9MM to the latest pre-built pre-release firmware, tx-R9M-f103c8-elrs-bl-v1.3.03-@b302689c.elrs and rx-R9MM-f103rb-elrs-bl-v1.3.03-@b302689c.elrs.  It has been running for 30 minutes so far.  My non-default parameters are Rx Ch Order = ETAR, Rx Ser Baudrate = 230400, Rx Snd Rc Channel = rc override.

**Comment by olliw42** [comment]
yes ... for totally unknown reasons the issue seems to have appeared just recently ... (we assume mavlinkX is enabled, right?)

could you also try by using self-compiled firmwares?

**Comment by brad112358** [comment]
Wasn't it observed in V1.3.01 pre-built?

**Comment by jlpoltrack** [comment]
> Wasn't it observed in V1.3.01 pre-built?

I did a git checkout back to 1.3.01 were it also appeared to be an issue, but after your note I also see on the latest pre-compiled binaries. Here's my summary at the moment, I usually get a crash between 2 and 5 minutes with an active serial connection.

R9M and R9MX - only change from default is 38400 baud on the Rx

![image](https://github.com/user-attachments/assets/209ac0a5-8dc6-4239-971a-ffea58805e6f)

**Comment by brad112358** [comment]
What does No mean above?  The text in this comment seems to say you do see the issue with pre-compiled 1.3.03, but then you have "No" everywhere in the table.

**Comment by olliw42** [comment]
I do see the issue for both v1.3.03 latest and with the code of the first commit of v1.3.01
in effect, when I do compile now it seems I always get the issue irrespective of what code version
have not tested the pre-compiled firmwares available in the github repo, but from the info gathered by others it seems to me that these pre-compiled files are ok

**Comment by jlpoltrack** [comment]
> What does No mean above? The text in this comment seems to say you do see the issue with pre-compiled 1.3.03, but then you have "No" everywhere in the table.

No means 'No' it doesn't work :)

**Comment by jlpoltrack** [comment]
To add further confusion, am trying a R9M as an Rx and it seems perfectly fine with a self-compiled build on MavlinkX.  Only change on the Rx side is 38400 baud.

**Comment by brad112358** [comment]
I switched to an R9MX receiver and quickly reproduced the problem.  I'll try with a locally built version.

**Comment by olliw42** [comment]
yo, it's totally weird and non-consistent ...

**Comment by olliw42** [comment]
the only things which seem to be "clear" (if that word can be used) is that
- it appears the issue is receiver-side
- it appears to be related to the compression part (if I undefine MAVLINKX_COMPRESSION it seems to work too)

**Comment by brad112358** [comment]
Note, I haven't compiled this in a while so I had to mark dronecan_dsdlc.py executable (chmod +x mLRS/modules/dronecan/dronecan_dsdlc/dronecan_dsdlc.py) and install the dronecan python library (python3 -m pip install dronecan) to get run_setup.py to work.  @olliw42 I suggest mark this file executable in git with "git update-index"

**Comment by jlpoltrack** [comment]
An MCU architecture thing?

- R9M + R9MM (Both STM32F1): Works
- R9M + R9M (Both STM32F1): Works
- R9M + R9MX (F1 + L4): Doesn't Work
- R9M + Generic (F1 + ESP8255): Doesn't Work
- Bandit + Generic (ESP32 + ESP8255): Doesn't Work

**Comment by olliw42** [comment]
>  suggest mark this file executable in git with "git update-index"

what does this mean?

**Comment by brad112358** [comment]
I reproduced the problem also on R9MX with a locally built version of git b302689c ( just to exactly match the pre-compiled version where it also failed for me).

**Comment by olliw42** [comment]
I believe to have narrowed it down to this part of the code https://github.com/olliw42/mLRS/blob/main/mLRS/Common/thirdparty/mavlinkx.h#L390-L414
when I make it to not be used the issue seems to go away ... I was suspecting like all places in the code, but not this one LOL

**Comment by brad112358** [comment]
> what does this mean?

Never mind.  I didn't realize that the dronecan_dsdlc submodule comes directly from the dronecan project.  I'll probably send them a PR to fix the permissions.

**Comment by brad112358** [comment]
> I believe to have narrowed it down to this part of the code https://github.com/olliw42/mLRS/blob/main/mLRS/Common/thirdparty/mavlinkx.h#L390-L414 when I make it to not be used the issue seems to go away ... I was suspecting like all places in the code, but not this one LOL

Buffer overrun?

**Comment by olliw42** [comment]
> Buffer overrun?

yes, this is the suspicion since ever, also for the old MavlinkX issue here https://github.com/olliw42/mLRS/issues/159 ... but all my starring at the code hasn't shown it to me ... but I may have starred too much at the wrong part of the code ...

... I have a feeling I see it now ...

**Comment by olliw42** [comment]
I think you guys also can check it's this part of the code, simply change this line https://github.com/olliw42/mLRS/blob/main/mLRS/Common/thirdparty/mavlinkx.h#L400 to `if (false && ....`

**Comment by jlpoltrack** [comment]
Yea, 10 minutes here with R9MX and looks good.

**Comment by olliw42** [comment]
so bounty ... how finds the buffer overwrite

have changed the len fields to uint16 already, to prevent an issue from this ... hasn't helped ... I f.ing just can't see it ...

**Comment by olliw42** [comment]
I give up for today ... just can't find the issue

might be we have to disable compression, without it just works for ever

**Comment by brad112358** [comment]
I don't see it yet either.  Though, the size of the len arguments and variables could obviously have caused some problems with the largest possible messages.

**Comment by olliw42** [comment]
pushed some changes to main, with the u16 changes in mavlinkx.h, and teh betafpv & bandit added

the issue still exists
it goes away when I do the `if (0 && fmavx_config_g.compression_enable ...` tweak on the receiver side (not needed on teh tx side)

I did test on Bandit & R9MX, need to see if it exists/goes away for Bandit & Generic900

which raises questions
- since compression is enabled only for 19 Hz, are there cases beyond those we tested so far there it does occur. I specifically wonder about 2.4. Ghz at 19 Hz
- is this the same as the gcc12 issue, i.e., does it go away also with the same change?

**Comment by jlpoltrack** [comment]
> * since compression is enabled only for 19 Hz, are there cases beyond those we tested so far there it does occur. I specifically wonder about 2.4. Ghz at 19 Hz

Seemingly okay on 2.4 | 19 Hz.  Testing with DIY E28 F1 Tx and SuperD Rx.

**Comment by rotorman** [comment]
> @rotorman out of desperation, you happen to have any idea on such an issue?

Is the problem only with FrSky gear (which I do not have)? Otherwise, no, I have not experienced mLRS drop the connection for an unknown reason.

**Comment by jlpoltrack** [comment]
> * is this the same as the gcc12 issue, i.e., does it go away also with the same change?

GCC 12 with compression disabled on R9MX seems okay...

**Comment by olliw42** [comment]
> > @rotorman out of desperation, you happen to have any idea on such an issue?
> 
> Is the problem only with FrSky gear (which I do not have)? Otherwise, no, I have not experienced mLRS drop the connection for an unknown reason.

I was actually hoping that you might have some insight into the typical traps when one thinks that a compiler seemingly doesn't do the code one thinks it should do according to the code lines ... the code looks all alright to me and it's not obvious why it would write into a wrong memory location ... yet it does.

**Comment by olliw42** [comment]
> > * is this the same as the gcc12 issue, i.e., does it go away also with the same change?
> 
> GCC 12 with compression disabled on R9MX seems okay...

so it's possible it's one and the same issue

**Comment by olliw42** [comment]
I'm still constantly working on this, and yesterday for a moment I was kind of convinced I finally found the culprit, I still actually haven't ...

it appears that the issue is `_fmavX_payload_compress()`. All protections I've added to check for out of bounds read/writes don't trigger ... whuich makes it more misterious.

At some point I had the idea to not compress, but to set the MAVLINKX_FLAGS_IS_COMPRESSED flag on the receiver side, so that the tx side attempts to decompress non-compressed data ... it's a sort of a stress test to the parser&decompressor ... and the result is: CATASTROPHIC! The tx undergoes reboots, and sometimes will just stop ...

ergo, the parser+compressor are NOT stress resistant. I guess that's the way I'm going now, I guess chances are that this issue and the other issues are related.

**Comment by olliw42** [comment]
@jlpoltrack @brad112358 @tmcadam 

so, again me ... and a more desparate me

this issue kind of upholds any further progress with the code (so far we could get around by not using the gcc12, but unfortunately the issue has now creept into the main code)

my setup is still a RM Bandit Micro as tx and R9MX as rx.

as you may have seen, I have pushed few more changes. There was a further array which was too small and thus could have been a point for an out-of-range memory access, corrected it but doesn't help. You also can see that I added catchers to kind of every single access to an array. NONE of them ever triggered or triggers for me.

I like to summarize what seems to be the "facts":
1. when the issue appears, the tx disconnects but the rx remnains connected
2. the rx still sends and the tx still receives
3. however, the sync word (and potentially other data, just checked for the sync word) which is received by the tx is incorrect and remains incorrect further on (and hence the tx refuses all further received frames)
4. the situation cannot be cured by repowering the tx
5. the situation can only be cured by repowering the rx

these "facts" make me believe that the issue is in the receiver side code. I'm not sure this conclusion is 100% true however, I can't see a loophole to the argument but me not seeing the loophole might be exactly the reason for not finding the issue.  

these appear to be also true (but might be missleading as reagrds to where the issue is located):
6. disabling mavlinkX or weaker, outcommenting `#define MAVLINKX_COMPRESSION` in the code for the receiver, makes the issue go away
7. disabling on the rx side only the compression but leaving on the decompression (by e.g. the `if(0 &&` trick) does not help, the issue remains
8. the recent changes to the size of some pos field (u16 instead of u8) seem to have helped in the sense that it subjectively feels like the issue happens now less soon ... but it eventually still happens (sometimes I have to wait for long, but over night or over work day always made it happen so far)
9. I have done tests with the stack-checker enabled on the rx, and there is no stack overflow (the stack remains less than half field)(stack size os 1k)
10. I did some more little tetest, e.g. changed the size of the working buffer fmavx_in_buf from 300 to 1024, or forced the mavlinkX functions to not be inlined, etc,. None helped.

I can't understand why none of the out-of-range catchers trigger, yet it appears that the compression code causes the  problem.

It is easy to see why the tx disconnects, one just needs to add some debug code to store and print out the sync_word received in the isr, which shows that it suddenly changes to incorrect values. This could be an issue in the tx code, but 4. & 5. suggest it's indeed the receiver sending frames with incorrect data.
However: to the day I have not managed to see the receiver doing this. That is, wherever I added debug code to print out what should be the sync_word in the transmitted frame, it prints the correct value ... even when the issue has happened.

Is anyone of you exoperienced with code checker like Valgrind or others (just googled this LOL)?
You know of some gcc flags we could/should use? (tried -Warray-bounds=2 but just found an msp error, which shouldn't have an effect)

--------

for your info, here is a dump of the deb output on the Tx side, which shows how the received syncword changes when the issue happens. It undergoes a chain of different values until it always ends up in 0x5220. (0x7C85 is the synword generated from the default bind phrase). The entries are (1) sync word as received in the isr, (2) rxFrame.sync_word, (3) txFrame.sync_word. As said, I did not yet manage to add dbg code to the rx side which would show me that the rx is indeed sending frames with these sync words.  

```
>1!ri x7C85 x7C85 x7C851<
<\n>
>1!ri x7C85 x7C85 x7C851<
<\n>
>1!ri x7C85 x7C85 x7C851<
>1!ri x7C85 x7C85 x7C851<
>1!ri x7C85 x7C85 x7C851<
>1!ri x7C85 x7C85 x7C851<
>1!r
>1!ri x05E2 x7C85 x7C85
>.1!ri x2C29 x7C85 x7C85
>1!ri x2C29 x7C85 x7C85
>1!ri x776F x7C85 x7C85
>1!ri x0340 x7C85 x7C85
>1!ri x0340 x7C85 x7C85
>1!ri x374B x7C85 x7C85
>1!ri x4043 x7C85 x7C85
>1!ri x4043 x7C85 x7C85
>1!ri x9DBF x7C85 x7C85
>1!ri x0100 x7C85 x7C85
>1!ri x0100 x7C85 x7C85
>1!ri xDB04 x7C85 x7C85
>1!ri xBF17 x7C85 x7C85
>1!ri xBF17 x7C85 x7C85
>1!ri x5DBD x7C85 x7C85
>1!ri x0C40 x7C85 x7C85
>1!ri x0C40 x7C85 x7C85
>1!ri xF93B x7C85 x7C85
>1!ri xEBBA x7C85 x7C85
>.1!ri xEBBA x7C85 x7C85
>1!ri x1763 x7C85 x7C85
>1!ri x0101 x7C85 x7C85
>1!ri x0101 x7C85 x7C85
>1!ri x5220 x7C85 x7C85
>1!ri x5220 x7C85 x7C85
>1!ri x5220 x7C85 x7C85
>1!ri x5220 x7C85 x7C85
>1!ri x5220 x7C85 x7C85
```

**Comment by brad112358** [comment]
Wow.  This is just plain nasty.  I read your last comment just before I went to sleep last night and I'll be honest; it invaded my dreams.  Unfortunately I didn't wake up with a solid hunch (which has happened to me on occasion)  Your reasoning and conclusions all look sound to me.

Were you able to fix the decompress code so it doesn't crash when fed garbage (like you did by marking uncompressed messages as compressed)?  It occurs to me that it and everything else in the receive path does need to be robust in the face of transmission errors as the various CRC checks can't eliminate absolutely all of these.  Considering the evidence that you may have reduced the frequency of the errors makes me wonder if the reason you see these so much less frequently now is because the remaining cases are triggered by undetected transmission errors.

Unfortunately, I don't think Valgrind or any similar tool is applicable to tiny embedded platforms like ours.  I have used/enhanced some much lighter weight custom buffer overrun and memory allocation/free debug libraries in the past, but they target mostly dynamically allocated memory and depended on having an MMU to catch access beyond or ahead of the allocated block, so are useless here.  In short, I am not aware of any applicable tools.

**Comment by olliw42** [comment]
I have this suspicion all time long, but I'm getting more and more convinced it's not actually the mavlinkx compression code, but something else which is just exposed by having it included

I've added this now (and some dbg code), to check more closely what it sends
![grafik](https://github.com/user-attachments/assets/eb5d8fe2-bac9-4821-aa29-64976e064580)
and it runs now since > 6 h ...  (with the other additions getting the issue could need 1h or so, but 6 h, that's long ...)

**Comment by olliw42** [comment]
I would not mind if I would find the source of the problem in my dreams ... :D

**Comment by brad112358** [comment]
Updating the sync word every time makes sense as a workaround, but obviously doesn't explain how it got corrupted in the first place.

You didn't respond about the decompression code?  Doesn't this need to be fixed too?  Granted, you probably don't have enough transmission errors in your test for bad data to make it past a 16 bit CRC in an hour since you were probably testing on the bench.   But at the edge of our range, this could be a real problem.  By my calculations, If an average of 1/4 of the radio messages have a couple of bit errors, it would only take about 87 minutes on average to encounter an undetected error which from what you said could be very bad.

**Comment by olliw42** [comment]
this piece of code does NOT update the sync_word every time ... it just reads it into a variable which later is when used to print it out on dbg

ah, sorry. Yes, the compression catastrophy was a short term thing ... it seems to have went away with the u8 to u16 conversions, especially this line was a clear bug with u8, since len can be 255: https://github.com/olliw42/mLRS/blob/main/mLRS/Common/thirdparty/mavlinkx.h#L894. But I must admit I can't say I fully understood the error mode in detail of what I was describing.

I think that for as long as we kind of can be sure that the compression code does not (i) hangs up, (ii) writes in incorrect memory locations or (iii) yields lengths which make other code to write out of memory, we can accept any nonsense the compression code might do ... and I really had catcher for out-of-range like everywhere ... not a single every triggered

**Comment by brad112358** [comment]
> this piece of code does NOT update the sync_word every time ... it just reads it into a variable which later is when used to print it out on dbg.

Oops.  Sorry.  So, just another example of how this really is a heisenbug then.

**Comment by olliw42** [comment]
so, after ca 8 h it now also failed ... in the Tx log I see exactly the same as reported, but in the rx log I see all sync_words which I print out to be perfectly ok ... I still can't manage to see it that the rx starts to send incorrect sync words ... despite the evidence a tx code bug?

I just don't get it

but we really need to find this, it holds up any further progress ...

**Comment by brad112358** [comment]
How is this possible if the problem is on the receiver end which seems the case given restarting the Tx doesn't fix it.  Somehow, the corruption happens in the SX1276 itself or during the SPI transfer?

**Comment by brad112358** [comment]
Perhaps some sort of timing sensitive issue affecting the driver?  The sequence of received incorrect sync words and that it gets stuck on 0x5220 really is strange though.

**Comment by jlpoltrack** [comment]
> Perhaps some sort of timing sensitive issue affecting the driver? The sequence of received incorrect sync words and that it gets stuck on 0x5220 really is strange though.

Just a random thought when you mention timing - the R9MX clock config seems to use the (internal) MSI (and not the XO on the board) but at same time - SPI is a synchronous protocol so shouldn't matter (well in my mind) if there's variations in the SPI clock speed.

**Comment by brad112358** [comment]
Both debug output examples show reaching 0x5250 after 24 rejected messages which exactly matches our 1.25 second connection timeout which makes me wonder if the data we are incorrectly sending may actually be coming from our received messages.

**Comment by brad112358** [comment]
Have we seen any indication of this issue or the problem with newer GCC versions on anything other than SX1276?

**Comment by olliw42** [comment]
> How is this possible if the problem is on the receiver end which seems the case given restarting the Tx doesn't fix it.

that's the logical contradiction I'm not getting along with all the the time ...

> Both debug output examples show reaching 0x5250 after 24 rejected messages which exactly matches our 1.25 second connection timeout 

oh, very well observed !! interesting, need to think about this

> Have we seen any indication of this issue or the problem with newer GCC versions on anything other than SX1276?

given the similarities we had associated this to the same issue seen earlier with mavlinkX on gcc12. If I recall here it was also especially for sx128x and FLRC. @jlpoltrack correct?

**Comment by jlpoltrack** [comment]
I first noticed on SX126x / G4: https://github.com/olliw42/mLRS/issues/159#issuecomment-2241102917 I think this would've been 31 Hz or FSK.

Also later could reproduce on STM32F1 / SX128x / FLRC.  Which indicated that it wasn't necessarily a compression thing...

**Comment by olliw42** [comment]
just reread the oter thread, there is lots of talk of a tx crash ... so, are the sympthos actually kind of very different ... and the only "similarity" is a presumed relation to mavlinkX?

**Comment by jlpoltrack** [comment]
Yes, MAVlinkX was the common piece.  Just highlighting why it was reported as a Tx crash, quote from other thread:

"The same issue appears - the connection looks good between Tx and Rx, however, as soon as the FC has initialized and starts emitting data the Tx crashes (no LEDs) and requires a power cycle. This doesn't seem to affect the Rx side - it just disconnects and shows a flashing red LED. Switching to Mavlink (instead of MavlinkX) shows the usual behavior."

**Comment by brad112358** [comment]
Sounds like it was crashing pretty fast. I wonder if any of your changes so far might have also made gcc12 better

**Comment by olliw42** [comment]
THX @jlpoltrack 

so, indeed quite different error pattern ... 
I too started to wonder if the gcc12 issue is now gone, there had been quite some bugs in the compression code removed, related to the u8 vs u16 thing
and I too now wonder if that is now "just" a sx1276 thing ... I guess we need to do some tests with the other sx hardware, using 19 Hz. Note though, running just few dozen minutes is not sufficient, one basically needs to run each test over night or during day work, like 12h or so ...

**Comment by olliw42** [comment]
so, started sx1262, mR900-30 receiver and tx kit, full erase then flashed with main as of now, changed power to min, set to 19 Hz and double checked mavlinkX
let's see tomorrow morning ...

**Comment by olliw42** [comment]
>12 h later: still going strong, no indication whatsoever of an issue

I'm going to do this test also for the m24-30 stuff ... but I'm kind of sure to know aht the outcome will be

so, it seems to be sx1276 specifc ... or hardware specific ... or both

**Comment by olliw42** [comment]
I went thorugh the thread and collected some info on hardware we got so far:

R9M and R9MX show issue
1.3.00 release looks good
1.3.01 self-compiled already bad

RM Bandit Micro and R9MX show issue
"strange fact, seems to be an issue only with the sx1276 (or sx1276 based devices)"
"it seems to exist for both the R9MX and Generic900"

rx Generic900 ->syncword  becomes 0x85D5
R9MX -> syncword becomes 0x5220

R9M ACCST and R9MM latest pre-built pre-release firmware, all good
"I switched to an R9MX receiver and quickly reproduced the problem. I'll try with a locally built version."
"I reproduced the problem also on R9MX with a locally built version"

R9M + R9MM (Both STM32F1): Works
R9M + R9M (Both STM32F1): Works
R9M + R9MX (F1 + L4): Doesn't Work
R9M + Generic (F1 + ESP8255): Doesn't Work
Bandit + Generic (ESP32 + ESP8255): Doesn't Work

"Seemingly okay on 2.4 | 19 Hz. Testing with DIY E28 F1 Tx and SuperD Rx."

**Comment by olliw42** [comment]
it was speculated that it could be spi communication with sx1276
the "nice" aspect of that is that it would explain why in the code I can't see the rx to change sync_word
but some things don't fit here too
- why only rx, not also tx
- why not only sporadically, but systematically, one bad communication and all communication wrong hencforth

**Comment by brad112358** [comment]
>  why not only sporadically, but systematically, one bad communication and all communication wrong hencforth
Good point which I suppose means it could be the sx1276 that is in a bad state.  Would be interesting to add a way to reinit only the sx1276 at will to see if that gets it going again.

**Comment by olliw42** [comment]
I was actually thinking of adding a rescue mode ... but this would require me to be able to detect the failure state on the rx ... which I didn't manage yet

**Comment by olliw42** [comment]
I will also say that I think that we either find that issue in a not too long distance or we are going to face a tough decission

MSP gets along, and also DroneCAN might be close ... and I think a next beta version is overdue anyway ... if we don't want to postpone until infinity we might have to exclude all sx1276 targest from such an release ...

**Comment by jlpoltrack** [comment]
> exclude all sx1276 targest from such an release

Has this been reproduced on MAVLink (non-X) + SX127x?

**Comment by olliw42** [comment]
> Has this been reproduced on MAVLink (non-X) + SX127x?

not by me, to me it seems outcommenting compression or disabling mavlinkX avoids the issue
disabling mavlinkX is IMHO however not desirable, since our mavlink link robustness depends on it
disabling compression would break backwards compatibility
IMHO main problem is a bit that this might be just anecdotical ... we would have to do long time tests for kind of each combination to be on the safe side (which I kind of do now for the other targets, each day and night a new combo)

**Comment by brad112358** [comment]
It has been slow, but, It seems to me that we (you) are still making progress in characterizing and isolating the problem.

I would suggest that we have not yet reached the point where we need to break compatibility or, worse, drop support for a fairly popular hardware platform.  Isn't it easy enough to deprecate compression without breaking compatibility?

For the next release, I would suggest disabling compression only on the sending end, leaving the decompressing code in place and do this only for SX127x.  If this avoids the problem in long running tests, we can, then recommend upgrading anything using SX127x and even if users upgrade only one end at a time, compatibility will be maintained and they will be no worse off than they are with the current release.

**Comment by olliw42** [comment]
> For the next release, I would suggest disabling compression only on the sending end, leaving the decompressing code in place

I had the same idea as this at least would leave backwards compatibility, but I found this to also show the issue. No viable option hence. IMHO.

**Comment by olliw42** [comment]
so, did some long time tests for
- mR24-30 tx kit & mR24-30 receiver: 14 h -> all good
- mR24-30 tx kit & RM RPTD4 receiver: 119 h -> all good

I then wanted to change the tx module to the betafpv 1W micro ... and I just get CATASTROPHIC behavior
- the RPTD4 receiver is quickly (couple dozen seconds) driven into a FAIL state (fast red blinking)
- too often the connection will not start properly

FOLKS: WE HAVE SERIOUS PROBLEMS ALL AROUND

to me it seems that we rather will have to drop all ELRS targets, and the sx127x STM32 targets ... I frankly observe just too many issues.

**Comment by olliw42** [comment]
as regards the issue itself, I start wondering if it's not an issue with the sx1276 driver which somehow over time crept in. Sometimes it feels to me like we are back before we had the AFC correction from Brad. Is the AFC stuff still working?
just brain storming

**Comment by jlpoltrack** [comment]
Since it sounds like compression plays a role (in some way) - will this be removed in the next release (1.4) ?

**Comment by olliw42** [comment]
> Since it sounds like compression plays a role (in some way) - will this be removed in the next release (1.4) ?

I would not like to disable it for targets where it is just working fine.

**Comment by olliw42** [comment]
the issue was identified, it is related to the tx module transmitting with substantial jitter
it could not be identified how it exactly could lead to a wrong sync wird being transmitted
the solution is to change the tx code such that it transmits with very low jitter
has been stress tested enourmously (see also discord)
closing
